sequenceDiagram
    participant B as Client (192.168.0.100)
    participant C as Server (192.168.0.102)

    Note over B, C: Fermeture de la connexion
    B->>C: 34. [SCTP] SHUTDOWN
    C->>B: 36. [SCTP] SHUTDOWN_ACK
    B->>C: 37. [SCTP] SHUTDOWN
    B->>C: 38. [SCTP] SHUTDOWN_COMPLETE
